### PR TITLE
add pratt newton method + tests

### PR DESCRIPTION
**Pull request by affans**
According to [this book ](https://www.taylorfrancis.com/books/mono/10.1201/EBK1439835906/circular-linear-regression-nikolai-chernov), the authors state 

image

Given a possible numerical instability, I've added an alternative method called `pratt_newton`. This enhances the package and allows users to use a method where the `:pratt` algorithm may not work properly. 

I plan on adding the `SVD` approach later on as well.

### CODE REVIEW

**Comment by affans** [comment]
I simply just added a new function, so nothing changed with existing functionality. I don't know why the last test is failing (perhaps due to a very old version of julia?)

**Comment by feanor12** [comment]
I think there is also an instability problem with the Taubins method. Some time ago I was looking into adding a more stable algorithm to find the eigenvalues, but I did not fully understand the one that was in this paper:  https://doi.org/10.1007/s10851-005-0482-8 
I am sure it is very similar to newtons method for Pratts algorithm, which should reliably find the smallest non-negative generalized eigenvalue.

**Comment by affans** [comment]
@feanor12 a quick question. as far as Julia packages go, do you need to tag the package for it to be updated in the Julia package registry? I'd like to delete my fork and just do a `add CircleFit` in my environment.

**Comment by feanor12** [comment]
I just requested a new release to be published so there should be an update soon.

**Comment by affans** [comment]
Okay perfect. Then I'll add the SVD in a bit later when I have more time... By the way, this was my first open source contribution! It's quite exciting and satisfying.

**Pull request merged**
